name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Esta versión'
        required: true
      dev_version:
        description: 'Siguiente versión'
        required: true

jobs:
  release:
    name: Liberar a Maven Central
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código.
        uses: actions/checkout@v4

      - name: Instalar Java 11.
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 11
          cache: maven
          server-id: central
          server-username: MAVEN_CENTRAL_USER
          server-password: MAVEN_CENTRAL_PASSWORD
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Importar llave GPG
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Liberar.
        run: ./mvnw -B release:prepare release:perform -DdevelopmentVersion=${{ github.event.inputs.dev_version }} -DreleaseVersion=${{ github.event.inputs.release_version }}
        env:
          MAVEN_CENTRAL_USER: ${{ secrets.MVN_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MVN_TOKEN }}
